#!/bin/bash
# calc_downld_plus_installr by David Weinman <david@weinman.com>

# This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.

if [ $# -eq 2 ]; then

  wget $1
  FNAME="$(echo $1 | awk -F/ '{print $(NF)}')"
  echo "[*] downloaded $FNAME"
  gcc $FNAME -o $2 -lm
  echo "[*] compiled $2"
  submit_calc $2
  echo "[*] submitted $2"

else

  echo "[!] argcount error. "
  echo "Usage: calc_installer <link_to_get_calc> <desired_calc_fname>"
  exit

fi

