#!/bin/bash


mkdir log/calc_scenario

FILE="$1"
LASTMODIFIED=$2

while [ 0 ]; do

  if [ python -c "import os,time; print time.ctime(os.path.getmtime('/tmp/calc_in_out'))" != "$LASTMODIFIED" ]; then

    INPUT="$(tail --lines=1 /tmp/calc_in_out)"
    cp gdb_script_front run_calc_gdb_script_.py.gdb
    echo "file $FILE
python
import string
myout = gdb.execute("r \"$($INPUT)\"", False, True)
" >> run_calc_gdb_script.py.gdb
    cp gdb_script_back gdb_tmp_back
    cat gdb_tmp_back >> run_calc_gdb_script.py.gdb
    rm gdb_tmp_back
    gdb -q -x run_calc_gdb_script.py.gdb >> tmp

    if grep -q 'killed' "./tmp" ; then

      NOW=$(date +%F--%R%p)
      cat tmp | grep "0x" > log/calc_scenario/crash_addr_$NOW.txt
      echo "$($INPUT):0:$(cat log/calc_scenario/crash_addr_$NOW.txt)" | nc scorebot 0000 # remember to change this line according to SB specs
      echo "$($INPUT):[!!] calculator crashed." | nc 10.0.0.8 2222 
      NOW=""
      rm tmp

    else

      NOW=$(date +%F--%R%p)
      mv tmp $NOW.txt
      echo "$($INPUT):1:$(cat $NOW.txt)" | nc scorebot 0000
      cat $NOW.txt | nc 10.0.0.8 2222
      NOW=""

    fi

    rm run_calc_gdb_script.py.gdb

  fi

done

