#!/bin/bash
# nc_server_reboot by David Weinman <david@weinman.com>

# This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.

if [ ! $# -eq 0 ]; then

  echo "wrong # of args."
  echo "Usage: defending_server_reboot or attacking_server_reboot"
  exit

fi
PID=$(ps -C nc -o pid=)
kill $PID

