#!/bin/bash
# nc_server_reboot by David Weinman <david@weinman.com>

# This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.

if [ ! $# -eq 0 ]; then

  echo "wrong # of args.
usage: scoring_server_reboot"
  exit

fi
PID=$(ps -C scoring_listener -o pid=)
kill $PID

