#!/usr/bin/python
"""
  scoreboard
  by David Weinman
  11/25/14, 4:30a

---
listens for any connection on
port 1234 and responds
with the contents of the score-
board file.
"""

"""
This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.
"""

import os
from socket import *

MAXDATASIZE = 5000
filename = "/tmp/scoring/answers"

serverPort = 1234

serverSocket = socket(AF_INET, SOCK_STREAM)

serverSocket.bind(('', serverPort))

serverSocket.listen(1)

print('listening on %d' % serverPort)

while 1:
	connectionSocket, addr = serverSocket.accept()
	#data = connectionSocket.recv(MAXDATASIZE)
	fh = open(filename, "r")
	data = fh.read()
	connectionSocket.sendall(data)
	fh.close()
	connectionSocket.close()

