#!/bin/bash
# start_attack_server by David Weinman <david@weinman.com>

# This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.


# if the pid is empty (server doesnt exist), start it
# on port 2222
if ! ps -C nc -F | grep -q "nc -l -k 2222"; then
	nc -l -k 2222 >> /tmp/calc_in_out &
fi


