#!/bin/bash

while [ 0 ]; do
    # get the pid of the server if it exists
    SRVR_PID=$(ps -C blueserver -o pid= )

    # if the pid is empty (server doesnt exist), start it
    # on port 1337
    if [ "$SRVR_PID" == "" ]; then

           blueserver

    fi
    sleep 1
done

SRVR_PID=""

