#!/bin/bash
# start_scoring_server by David Weinman <david@weinman.com>

# This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.

touch /tmp/calc_in_out
scoring_listener &

