#!/bin/bash
# submit_calc by David Weinman <david@weinman.com>

# This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.


if [ ! $1 == "" ]; then

  if [ ! -e $1 ]; then # if the given calc doesn't exist, error!

    echo "[!!] your calculator filename is invalid."
    exit

  else 	# if the calc exists, start the loop that accepts
        # attacking team input and sends it off to the scorebot
    get_attacker_input $1 2> get_input_log.txt &

    if ! ps -C nc -F | grep -q "nc -l -k 1337"; then

      start_defense_server

    fi

  fi

else

  echo "Usage: submit_calc </path/to/calculator_filename>"

fi
