#!/bin/bash

if [ ! $1 == "" ]; then

  if [ ! -e $1 ]; then # if the given calc doesn't exist, error!

    echo "[!!] your calculator filename is invalid."
    exit

  else 	# if the calc exists, start the loop that accepts
        # attacking team input and sends it off to the scorebot
    echo "" > /tmp/calc_in_out
    rm /tmp/calc_in_out
    touch /tmp/calc_in_out
    get_attacker_input $1 $(wc -l /tmp/calc_in_out | awk '{print $(NF - 1)}') &

  fi

else

  echo "Usage: $0 calculator_filename"

fi

#
# Calc Scenario Scorebot Submition Algorithm --
# 1. see if we were given a calculator, if so - run
#    the get_attacker_input script in the background
#

