#!/bin/bash
# update_calc by David Weinman <david@weinman.com>

# This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.


if [ ! $# -eq 1 ]; then

  echo "wrong # of args.
usage: update_calc </path/to/calc_filename>"
  exit

fi

PID=$(ps -C get_attacker_input -o pid=)
kill $PID
rm gdb_script_front gdb_script_back run_calc_gdb_script.py.gdb input_file.txt
rm /tmp/calc_in_out
touch /tmp/calc_in_out
submit_calc $1
PID=""

