#!/bin/bash

if [ ! $# -eq 1 ]; then

  echo "wrong # of args.
usage: $0 path_to_calc_to_submit"
  exit

fi

PID=$(ps -C get_attacker_input -o pid=)
kill PID
echo "" > /tmp/calc_in_out
submit_calc $1
PID=""

